apiVersion: v1
kind: Service
metadata:
  name: web-demo
spec:
  type: NodePort
  selector:
    app: web-demo
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30008
